### ISSUE TITLE
What is minimum version of php is required for this library?

### ISSUE THREAD

**Issue by kumargowdaa** [shyim/opensearch-php-dsl#7]
What is minimum version of php is required for this library?

I'm currently using php 7.3 version, this library is giving error.
Can you please help me in this ASAP.
Thank you.

**Comment by shyim** [comment]
PHP 7.4 is min version

**Comment by kumargowdaa** [comment]
@shyim thank you.

![PXL_20230724_092511906](https://github.com/shyim/opensearch-php-dsl/assets/17003296/34b05829-924a-4692-95f4-af0529435588)

Can you please look into the above image, in that line no 23 showing error, what's the issue with this?

**Comment by shyim** [comment]
I don't know what your IDE is doing here. Maybe hover over the line and see if it highlighted something in the text.
