### ISSUE TITLE
MinScore must be float type

### ISSUE THREAD

**Issue by smartkarp** [shyim/opensearch-php-dsl#9]
In class` OpenSearchDSL/Search` extra typing for property `$minScore`. This property mark as `?int` but for query need `?float`.

**Comment by shyim** [comment]
Did you solved your problem?

**Comment by shyim** [comment]
Quick google says it's float 🤔

**Comment by mhgtlc** [comment]
@shyim it has to be float, can you please fix it?
https://github.com/shyim/opensearch-php-dsl/blob/main/src/Search.php#L106

**Comment by shyim** [comment]
see https://github.com/shyim/opensearch-php-dsl/releases/tag/1.1.0
